# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: master.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import worker_pb2 as worker__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='master.proto',
  package='',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n\x0cmaster.proto\x1a\x0cworker.proto\"\x1c\n\x0cping_request\x12\x0c\n\x04\x64\x61ta\x18\x01 \x01(\t\"\x1d\n\rping_response\x12\x0c\n\x04\x64\x61ta\x18\x01 \x01(\t\"(\n\x0e\x66inal_response\x12\x16\n\x06result\x18\x01 \x03(\x0b\x32\x06.tuple\"1\n\x07\x61\x64\x64ress\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\n\n\x02ip\x18\x02 \x01(\t\x12\x0c\n\x04port\x18\x03 \x01(\x05\"l\n\x07request\x12\x19\n\x07workers\x18\x01 \x03(\x0b\x32\x08.address\x12\x17\n\x05store\x18\x02 \x01(\x0b\x32\x08.address\x12\r\n\x05map_f\x18\x03 \x01(\t\x12\x10\n\x08reduce_f\x18\x04 \x01(\t\x12\x0c\n\x04path\x18\x05 \x01(\t2g\n\x06Master\x12.\n\x0bping_master\x12\r.ping_request\x1a\x0e.ping_response\"\x00\x12-\n\x0erun_map_reduce\x12\x08.request\x1a\x0f.final_response\"\x00\x62\x06proto3')
  ,
  dependencies=[worker__pb2.DESCRIPTOR,])




_PING_REQUEST = _descriptor.Descriptor(
  name='ping_request',
  full_name='ping_request',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='data', full_name='ping_request.data', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=30,
  serialized_end=58,
)


_PING_RESPONSE = _descriptor.Descriptor(
  name='ping_response',
  full_name='ping_response',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='data', full_name='ping_response.data', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=60,
  serialized_end=89,
)


_FINAL_RESPONSE = _descriptor.Descriptor(
  name='final_response',
  full_name='final_response',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='result', full_name='final_response.result', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=91,
  serialized_end=131,
)


_ADDRESS = _descriptor.Descriptor(
  name='address',
  full_name='address',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='name', full_name='address.name', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='ip', full_name='address.ip', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='port', full_name='address.port', index=2,
      number=3, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=133,
  serialized_end=182,
)


_REQUEST = _descriptor.Descriptor(
  name='request',
  full_name='request',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='workers', full_name='request.workers', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='store', full_name='request.store', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='map_f', full_name='request.map_f', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='reduce_f', full_name='request.reduce_f', index=3,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='path', full_name='request.path', index=4,
      number=5, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=184,
  serialized_end=292,
)

_FINAL_RESPONSE.fields_by_name['result'].message_type = worker__pb2._TUPLE
_REQUEST.fields_by_name['workers'].message_type = _ADDRESS
_REQUEST.fields_by_name['store'].message_type = _ADDRESS
DESCRIPTOR.message_types_by_name['ping_request'] = _PING_REQUEST
DESCRIPTOR.message_types_by_name['ping_response'] = _PING_RESPONSE
DESCRIPTOR.message_types_by_name['final_response'] = _FINAL_RESPONSE
DESCRIPTOR.message_types_by_name['address'] = _ADDRESS
DESCRIPTOR.message_types_by_name['request'] = _REQUEST
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

ping_request = _reflection.GeneratedProtocolMessageType('ping_request', (_message.Message,), {
  'DESCRIPTOR' : _PING_REQUEST,
  '__module__' : 'master_pb2'
  # @@protoc_insertion_point(class_scope:ping_request)
  })
_sym_db.RegisterMessage(ping_request)

ping_response = _reflection.GeneratedProtocolMessageType('ping_response', (_message.Message,), {
  'DESCRIPTOR' : _PING_RESPONSE,
  '__module__' : 'master_pb2'
  # @@protoc_insertion_point(class_scope:ping_response)
  })
_sym_db.RegisterMessage(ping_response)

final_response = _reflection.GeneratedProtocolMessageType('final_response', (_message.Message,), {
  'DESCRIPTOR' : _FINAL_RESPONSE,
  '__module__' : 'master_pb2'
  # @@protoc_insertion_point(class_scope:final_response)
  })
_sym_db.RegisterMessage(final_response)

address = _reflection.GeneratedProtocolMessageType('address', (_message.Message,), {
  'DESCRIPTOR' : _ADDRESS,
  '__module__' : 'master_pb2'
  # @@protoc_insertion_point(class_scope:address)
  })
_sym_db.RegisterMessage(address)

request = _reflection.GeneratedProtocolMessageType('request', (_message.Message,), {
  'DESCRIPTOR' : _REQUEST,
  '__module__' : 'master_pb2'
  # @@protoc_insertion_point(class_scope:request)
  })
_sym_db.RegisterMessage(request)



_MASTER = _descriptor.ServiceDescriptor(
  name='Master',
  full_name='Master',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  serialized_start=294,
  serialized_end=397,
  methods=[
  _descriptor.MethodDescriptor(
    name='ping_master',
    full_name='Master.ping_master',
    index=0,
    containing_service=None,
    input_type=_PING_REQUEST,
    output_type=_PING_RESPONSE,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='run_map_reduce',
    full_name='Master.run_map_reduce',
    index=1,
    containing_service=None,
    input_type=_REQUEST,
    output_type=_FINAL_RESPONSE,
    serialized_options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_MASTER)

DESCRIPTOR.services_by_name['Master'] = _MASTER

# @@protoc_insertion_point(module_scope)
